// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9NuwG7QzTTI4eAVG72QVLKNed9c-xGXo',
    appId: '1:925397458937:web:544e9b3f093454879fa728',
    messagingSenderId: '925397458937',
    projectId: 'flutter-app-distribution-6a9c5',
    authDomain: 'flutter-app-distribution-6a9c5.firebaseapp.com',
    databaseURL: 'https://flutter-app-distribution-6a9c5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-distribution-6a9c5.appspot.com',
    measurementId: 'G-9MSKS3ZV94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5jFmZWaDPZ8SEfQAzONou-rkPHGNCv0Q',
    appId: '1:925397458937:android:58f7c4313ae753039fa728',
    messagingSenderId: '925397458937',
    projectId: 'flutter-app-distribution-6a9c5',
    databaseURL: 'https://flutter-app-distribution-6a9c5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-distribution-6a9c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpAFuPXdK2_MmgBHwSGqUe96itM5RExTc',
    appId: '1:925397458937:ios:f89929f29c7c2ba29fa728',
    messagingSenderId: '925397458937',
    projectId: 'flutter-app-distribution-6a9c5',
    databaseURL: 'https://flutter-app-distribution-6a9c5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-distribution-6a9c5.appspot.com',
    iosBundleId: 'com.example.graduationProject2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9NuwG7QzTTI4eAVG72QVLKNed9c-xGXo',
    appId: '1:925397458937:web:76a6fab745d4f4f99fa728',
    messagingSenderId: '925397458937',
    projectId: 'flutter-app-distribution-6a9c5',
    authDomain: 'flutter-app-distribution-6a9c5.firebaseapp.com',
    databaseURL: 'https://flutter-app-distribution-6a9c5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-distribution-6a9c5.appspot.com',
    measurementId: 'G-Z3LMFKN37C',
  );

}