# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Android App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
   
    firebase_app_distribution(
    app: "1:925397458937:android:58f7c4313ae753039fa728",
    firebase_cli_token:"1//036ZKz4GpeN_aCgYIARAAGAMSNwF-L9IrwEbmhXPZXVrxRPF3047x1VWLF2Xt4MPqNlyLfqOjVggBPmwgbhKOSQ1ManIdBn3IXVQ",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "iotdeveloper2024@gmail.com",
    release_notes: "Testing something with GitHub Actions, trying to push directly from master branch"

    #groups: "qa-team, trusted-testers"
  )
   
  end

     #****** ahmed commeted it as like omer ahmed ******* ##

 # desc "Submit a new Beta Build to Crashlytics Beta"
 # lane :beta do
 #   gradle(task: "clean assembleRelease")
 #   crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
